// Code generated by mdatagen. DO NOT EDIT.

package samplemigrationscraper

import (
	"go.opentelemetry.io/collector/cmd/mdatagen/internal/samplemigrationscraper/internal/metadata"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/scraper/scraperhelper"
)

// Configuration for the Sample Migration Scraper.
type Config struct {
	// MetricsBuilderConfig is a configuration for sample metrics builder.
	metadata.MetricsBuilderConfig `mapstructure:",squash"`
	// ControllerConfig defines common settings for a scraper controller configuration. Scraper controller receivers can embed this struct, instead of receiver.Settings, and extend it with more fields if needed.
	scraperhelper.ControllerConfig `mapstructure:",squash"`
	// Whether to emit legacy metric names alongside new ones.
	EmitLegacyMetrics bool `mapstructure:"emit_legacy_metrics"`
}

func createDefaultConfig() component.Config {
	return &Config{
		MetricsBuilderConfig: metadata.NewDefaultMetricsBuilderConfig(),
		EmitLegacyMetrics:    false,
	}
}
